### ISSUE TITLE
Support for passing in HttpClient

### ISSUE THREAD

**Issue by jacobslusser** [alexanderkozlenko/json-rpc-client#27]
### Summary

The project looks good so far. Nice job.

It looks to me like the `HttpClient` is constructed internally and there is no way to pass it in to reuse an existing instance. Not reusing instances (and sometimes reusing them) can lead to a lot of issues; see: [https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/).

### Outcome

It would be nice if the `JsonRpcClient` or `JsonRpcClientFactory` would allow the ability to pass in an existing `HttpClient` instance. 

### Additional Information

I'm specifically looking for this feature so I can use it from ASP.NET Core. In ASP.NET Core, there is already support for pooling `HttpClient` instances; see: [https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#what-is-httpclientfactory](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#what-is-httpclientfactory). 

I don't think we need a specific version of this library for ASP.NET Core -- adding the ability to pass in an `HttpClient` should be enough and then developers can use that with the standard DI container to make it all work.

**Comment by alexanderkozlenko** [comment]
@jacobslusser, thank you for the feedback!

There are a few constructors in `JsonRpcClient` which accept an instance of [HttpMessageInvoker](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessageinvoker?view=netcore-2.2):

- [`JsonRpcClient(string, JsonSerializer, HttpMessageInvoker, JsonRpcCompatibilityLevel)`](https://github.com/alexanderkozlenko/json-rpc-client/blob/master/src/Anemonis.JsonRpc.ServiceClient/JsonRpcClient.cs#L25)
- [`JsonRpcClient(string, HttpMessageInvoker, JsonRpcCompatibilityLevel)`](https://github.com/alexanderkozlenko/json-rpc-client/blob/master/src/Anemonis.JsonRpc.ServiceClient/JsonRpcClient.cs#L68)
- [`JsonRpcClient(Uri, JsonSerializer, HttpMessageInvoker, JsonRpcCompatibilityLevel)`](https://github.com/alexanderkozlenko/json-rpc-client/blob/master/src/Anemonis.JsonRpc.ServiceClient/JsonRpcClient.cs#L90)
- [`JsonRpcClient(Uri, HttpMessageInvoker, JsonRpcCompatibilityLevel)`](https://github.com/alexanderkozlenko/json-rpc-client/blob/master/src/Anemonis.JsonRpc.ServiceClient/JsonRpcClient.cs#L133)

 Thus, you can pass an instance of `HttpClient` (actually, this approach is used in solution's unit tests). Also, `JsonRpcClientFactory` has a constructor, which accepts an instance of the `JsonRpcClient` type: 

- [`Create<T>(JsonRpcClient)`](https://github.com/alexanderkozlenko/json-rpc-client/blob/master/src/Anemonis.JsonRpc.ServiceClient/JsonRpcClientFactory.cs#L29)

So, technically, you can already use `JsonRpcClient` and `JsonRpcClientFactory` types with a custom instance of `HttpClient` object.

**Comment by jacobslusser** [comment]
Thanks for your quick reply. This looks like what I need. I'll take a look.
